
spring.application.name=UserService
server.port=8092

spring.datasource.url=jdbc:mysql://localhost:3306/jbdl8_userdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Piyush@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ===============================
# Redis Cloud Configuration
# ===============================

#spring.redis.host=redis-14088.crce263.ap-south-1-1.ec2.cloud.redislabs.com
#spring.redis.port=14088
#spring.redis.username=default
#spring.redis.password=qHXX0qppffFcBi4egTjJYxxHlmO28kZT
#spring.redis.ssl=true
#spring.redis.timeout=5000






#spring.autoconfiguration.exclude=org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
# Disable Redis for now
# spring.data.redis.host=localhost
# spring.data.redis.port=6379
